# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: GRAPA
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  GRAPA is an associate team between Gallinette and PLEIAD that wants to extend the reach of gradual typing to full-fledged type theories in order to support smooth certified programming in a new generation of proof assistants.
domain: pleiad.github.io
baseurl: '/grapa-website'
url: https://pleiad.github.io
permalink: pretty
palette:
  bg:
    dark: sky-900
    light: sky-300
    medium: sky-600 
    accent: amber-500
  text: 
    dark: text-neutral-900
    light: text-neutral-500
    medium: text-neutral-700
    accent: amber-500

# Site navigation
navigation_header:
- title: Home
  url: /
- title: Team
  url: /team/
- title: Publications
  url: /publications/
- title: Activities
  url: /activities/

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Github Pages
gem "github-pages", "~> 228", group: :jekyll_plugins

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
